import type { Category, Product, Customer, Order, Employee, RewardRule } from "./types";

// ============================================================
// MOCK DATA — Menú real Rossy Gourmet
// Reemplazar llamadas con Supabase cuando esté configurado
// ============================================================

export const CATEGORIES: Category[] = [
  { id: "ensaladas",     name: "Ensaladas y Frescos",      emoji: "🥗", sortOrder: 1 },
  { id: "guarniciones",  name: "Guarniciones y Pastas",    emoji: "🍚", sortOrder: 2 },
  { id: "especiales",    name: "Especiales y Botanas",     emoji: "🍖", sortOrder: 3 },
  { id: "rollos-salados",name: "Rollos Primavera Salados", emoji: "🌯", sortOrder: 4 },
  { id: "rollos-dulces", name: "Rollos Primavera Dulces",  emoji: "🍬", sortOrder: 5 },
];

export const PRODUCTS: Product[] = [
  // ── Ensaladas y Frescos (250 g) ────────────────────────────
  {
    id: "rajas-verdes",
    categoryId: "ensaladas",
    name: "Rajas Verdes",
    description: "Aguacate, cebolla y chile cuaresmeño",
    price: 50,
    imageEmoji: "🌶️",
    unit: "250 g",
    available: true,
  },
  {
    id: "rajas-manzano",
    categoryId: "ensaladas",
    name: "Rajas de Manzano",
    description: "Aguacate, cebolla, chile manzano y habanero",
    price: 50,
    imageEmoji: "🌶️",
    unit: "250 g",
    available: true,
  },
  {
    id: "pico-gallo",
    categoryId: "ensaladas",
    name: "Pico de Gallo",
    description: "Jitomate, aguacate y cebolla",
    price: 50,
    imageEmoji: "🍅",
    unit: "250 g",
    available: true,
  },
  {
    id: "sopa-fria",
    categoryId: "ensaladas",
    name: "Sopa Fría Normal",
    description: "Pasta con mayonesa y jamón",
    price: 45,
    imageEmoji: "🥗",
    unit: "250 g",
    available: true,
  },
  {
    id: "sopa-fria-pina",
    categoryId: "ensaladas",
    name: "Sopa Fría con Piña",
    description: "Pasta con mayonesa, jamón y piña",
    price: 45,
    imageEmoji: "🍍",
    unit: "250 g",
    available: true,
  },
  {
    id: "ensalada-rusa",
    categoryId: "ensaladas",
    name: "Ensalada Rusa",
    description: "Zanahoria, chícharo, papa y mayonesa",
    price: 50,
    imageEmoji: "🥕",
    unit: "250 g",
    available: true,
  },
  {
    id: "lechuga-preparada",
    categoryId: "ensaladas",
    name: "Lechuga Preparada",
    description: "Lechuga desinfectada, jitomate cherry, jícama y zanahoria",
    price: 25,
    imageEmoji: "🥬",
    unit: "250 g",
    available: true,
  },
  {
    id: "nopal-natural",
    categoryId: "ensaladas",
    name: "Nopal Natural",
    description: "Nopal hervido con cilantro y cebolla",
    price: 40,
    imageEmoji: "🌵",
    unit: "250 g",
    available: true,
  },
  {
    id: "nopal-chile",
    categoryId: "ensaladas",
    name: "Nopal con Chile",
    description: "Nopal frito con cilantro, cebolla y chile de árbol",
    price: 40,
    imageEmoji: "🌶️",
    unit: "250 g",
    available: true,
  },
  {
    id: "habas",
    categoryId: "ensaladas",
    name: "Habas",
    description: "Habas hervidas con cebolla y cilantro",
    price: 40,
    imageEmoji: "🫘",
    unit: "250 g",
    available: true,
  },
  {
    id: "quelite",
    categoryId: "ensaladas",
    name: "Quelite",
    description: "Quelites fritos con cebolla",
    price: 45,
    imageEmoji: "🌿",
    unit: "250 g",
    available: true,
  },
  {
    id: "champinon-escabeche",
    categoryId: "ensaladas",
    name: "Champiñón en Escabeche",
    description: "Champiñón en escabeche",
    price: 50,
    imageEmoji: "🍄",
    unit: "250 g",
    available: true,
  },
  {
    id: "coliflor-escabeche",
    categoryId: "ensaladas",
    name: "Coliflor en Escabeche",
    description: "Coliflor en escabeche",
    price: 45,
    imageEmoji: "🥦",
    unit: "250 g",
    available: true,
  },
  {
    id: "chiles-tocino",
    categoryId: "ensaladas",
    name: "Chiles con Tocino",
    description: "Chile jalapeño relleno de queso y envuelto en tocino",
    price: 35,
    imageEmoji: "🥓",
    unit: "pieza",
    available: true,
  },
  {
    id: "chile-relleno",
    categoryId: "ensaladas",
    name: "Chile Relleno",
    description: "Chile poblano relleno de queso, capeado",
    price: 40,
    imageEmoji: "🫑",
    unit: "pieza",
    available: true,
  },

  // ── Guarniciones y Pastas (250 g) ─────────────────────────
  {
    id: "arroz-rojo",
    categoryId: "guarniciones",
    name: "Arroz Rojo",
    description: "Arroz rojo con jitomate, chícharo y zanahoria",
    price: 30,
    imageEmoji: "🍚",
    unit: "250 g",
    available: true,
  },
  {
    id: "arroz-chino",
    categoryId: "guarniciones",
    name: "Arroz Chino",
    description: "Arroz con salsa de soya, germen de soya y pollo",
    price: 45,
    imageEmoji: "🍳",
    unit: "250 g",
    available: true,
  },
  {
    id: "espagueti",
    categoryId: "guarniciones",
    name: "Espagueti",
    description: "Espagueti estilo oriental con verduras",
    price: 45,
    imageEmoji: "🍝",
    unit: "250 g",
    available: true,
  },
  {
    id: "verdura-horno",
    categoryId: "guarniciones",
    name: "Verdura al Horno",
    description: "Verdura al horno con aceite de oliva",
    price: 40,
    imageEmoji: "🥦",
    unit: "250 g",
    available: true,
  },
  {
    id: "papas-horno",
    categoryId: "guarniciones",
    name: "Papas al Horno",
    description: "Papas cambray con finas hierbas",
    price: 40,
    imageEmoji: "🥔",
    unit: "250 g",
    available: true,
  },
  {
    id: "papas-horno-chile",
    categoryId: "guarniciones",
    name: "Papa al Horno con Chile",
    description: "Papas cambray con finas hierbas y chile de árbol",
    price: 40,
    imageEmoji: "🌶️",
    unit: "250 g",
    available: true,
  },

  // ── Especiales y Botanas (250 g) ──────────────────────────
  {
    id: "pata-tostada",
    categoryId: "especiales",
    name: "Pata para Tostada",
    description: "Pata de res con col",
    price: 60,
    imageEmoji: "🍖",
    unit: "250 g",
    available: true,
  },
  {
    id: "pata-res",
    categoryId: "especiales",
    name: "Pata de Res",
    description: "Pata de res en escabeche",
    price: 75,
    imageEmoji: "🍖",
    unit: "250 g",
    available: true,
  },
  {
    id: "molleja",
    categoryId: "especiales",
    name: "Molleja",
    description: "Mollejas hervidas y fritas con chile de árbol",
    price: 70,
    imageEmoji: "🍗",
    unit: "250 g",
    available: true,
  },

  // ── Rollos Primavera Salados (pieza) ──────────────────────
  {
    id: "rollo-hawaiano",
    categoryId: "rollos-salados",
    name: "Rollo Primavera Hawaiano",
    description: "Piña, queso y jamón",
    price: 20,
    imageEmoji: "🌯",
    unit: "pieza",
    available: true,
  },
  {
    id: "rollo-pollo-verdura",
    categoryId: "rollos-salados",
    name: "Rollo Primavera Pollo con Verdura",
    description: "Pollo y verduras",
    price: 20,
    imageEmoji: "🌯",
    unit: "pieza",
    available: true,
  },
  {
    id: "rollo-champinon-queso",
    categoryId: "rollos-salados",
    name: "Rollo Primavera Champiñón con Queso",
    description: "Champiñón y queso",
    price: 20,
    imageEmoji: "🌯",
    unit: "pieza",
    available: true,
  },
  {
    id: "rollo-pastor",
    categoryId: "rollos-salados",
    name: "Rollo Primavera Carne al Pastor",
    description: "Pastor, piña y queso",
    price: 20,
    imageEmoji: "🌯",
    unit: "pieza",
    available: true,
  },
  {
    id: "rollo-pastor-pollo",
    categoryId: "rollos-salados",
    name: "Rollo Primavera Pastor con Pollo",
    description: "Pastor con pollo, piña y queso",
    price: 20,
    imageEmoji: "🌯",
    unit: "pieza",
    available: true,
  },
  {
    id: "rollo-rajas",
    categoryId: "rollos-salados",
    name: "Rollo Primavera Rajas con Queso",
    description: "Rajas y queso",
    price: 20,
    imageEmoji: "🌯",
    unit: "pieza",
    available: true,
  },
  {
    id: "rollo-pepperoni",
    categoryId: "rollos-salados",
    name: "Rollo Primavera Pepperoni",
    description: "Pepperoni y queso",
    price: 20,
    imageEmoji: "🌯",
    unit: "pieza",
    available: true,
  },

  // ── Rollos Primavera Dulces (pieza) ───────────────────────
  {
    id: "rollo-zarzamora",
    categoryId: "rollos-dulces",
    name: "Rollo Primavera Zarzamora",
    description: "Zarzamora y queso Philadelphia",
    price: 20,
    imageEmoji: "🫐",
    unit: "pieza",
    available: true,
  },
  {
    id: "rollo-pina-queso",
    categoryId: "rollos-dulces",
    name: "Rollo Primavera Piña con Queso",
    description: "Piña y queso Philadelphia",
    price: 20,
    imageEmoji: "🍍",
    unit: "pieza",
    available: true,
  },
];

// ── Clientes y empleados mock (sin cambios) ────────────────
export const CUSTOMERS: Customer[] = [
  {
    id: "c001",
    name: "Ana López",
    phone: "5551234567",
    email: "ana@email.com",
    stamps: 3,
    totalOrders: 8,
    totalSpent: 1340,
    createdAt: "2024-09-15T10:00:00Z",
  },
  {
    id: "c002",
    name: "Carlos Ramírez",
    phone: "5559876543",
    email: "carlos@email.com",
    stamps: 5,
    totalOrders: 12,
    totalSpent: 2100,
    createdAt: "2024-07-20T12:00:00Z",
  },
  {
    id: "c003",
    name: "María González",
    phone: "5554445566",
    stamps: 1,
    totalOrders: 3,
    totalSpent: 480,
    createdAt: "2025-01-10T09:00:00Z",
  },
  {
    id: "c004",
    name: "Roberto Vega",
    phone: "5557778899",
    email: "rvega@email.com",
    stamps: 4,
    totalOrders: 9,
    totalSpent: 1760,
    createdAt: "2024-11-05T15:00:00Z",
  },
];

export const EMPLOYEES: Employee[] = [
  {
    id: "e001",
    name: "Rosario Méndez",
    phone: "5551112222",
    role: "admin",
    active: true,
    todaySales: 4,
    totalSales: 1250,
    lastSaleAt: "2026-06-12T13:45:00Z",
    accessLink: "https://rossygourmet.com/mostrador?token=abc123",
  },
  {
    id: "e002",
    name: "Luis Herrera",
    phone: "5553334444",
    role: "cajero",
    active: true,
    todaySales: 7,
    totalSales: 890,
    lastSaleAt: "2026-06-12T14:10:00Z",
    accessLink: "https://rossygourmet.com/mostrador?token=def456",
  },
  {
    id: "e003",
    name: "Sofía Ruiz",
    phone: "5555556666",
    role: "cocina",
    active: true,
    todaySales: 0,
    totalSales: 320,
    lastSaleAt: "2026-06-11T18:00:00Z",
  },
  {
    id: "e004",
    name: "Miguel Torres",
    phone: "5557778880",
    role: "repartidor",
    active: false,
    todaySales: 0,
    totalSales: 150,
  },
];

export const ORDERS: Order[] = [
  {
    id: "ORD-001",
    createdAt: "2026-06-12T11:30:00Z",
    customer: CUSTOMERS[0],
    items: [
      { product: PRODUCTS[0], quantity: 2, notes: "Sin cebolla" },
      { product: PRODUCTS[5], quantity: 1 },
    ],
    deliveryType: "delivery",
    deliveryAddress: {
      street: "Av. Central 45",
      colonia: "Centro",
      ciudad: "Coacalco",
      cp: "55700",
    },
    status: "preparando",
    paymentMethod: "transferencia",
    paymentStatus: "pagado",
    subtotal: 150,
    total: 150,
    employeeId: "e001",
    source: "online",
  },
  {
    id: "ORD-002",
    createdAt: "2026-06-12T12:00:00Z",
    customer: CUSTOMERS[1],
    items: [
      { product: PRODUCTS[16], quantity: 2 },
      { product: PRODUCTS[22], quantity: 1 },
    ],
    deliveryType: "pickup",
    status: "nuevo",
    paymentMethod: "pendiente",
    paymentStatus: "pendiente",
    subtotal: 160,
    total: 160,
    employeeId: "e002",
    source: "mostrador",
  },
  {
    id: "ORD-003",
    createdAt: "2026-06-12T12:45:00Z",
    customer: CUSTOMERS[2],
    items: [
      { product: PRODUCTS[24], quantity: 4 },
      { product: PRODUCTS[30], quantity: 2 },
    ],
    deliveryType: "pickup",
    status: "listo",
    paymentMethod: "efectivo",
    paymentStatus: "pagado",
    subtotal: 120,
    total: 120,
    source: "kiosko",
  },
  {
    id: "ORD-004",
    createdAt: "2026-06-12T13:15:00Z",
    customer: CUSTOMERS[3],
    items: [
      { product: PRODUCTS[2], quantity: 1 },
      { product: PRODUCTS[7], quantity: 1 },
    ],
    deliveryType: "delivery",
    deliveryAddress: {
      street: "Calle Jazmín 12",
      colonia: "Las Flores",
      ciudad: "Tultitlán",
      cp: "54900",
    },
    status: "aceptado",
    paymentMethod: "efectivo",
    paymentStatus: "pendiente",
    subtotal: 90,
    total: 90,
    employeeId: "e001",
    source: "online",
  },
];

export const REWARD_RULES: RewardRule[] = [
  { stampsRequired: 5, reward: "Postre gratis a elegir" },
  { stampsRequired: 10, reward: "Producto gratis a elegir" },
];

// ── Utilidades ─────────────────────────────────────────────
export function getProductsByCategory(categoryId: string): Product[] {
  return PRODUCTS.filter((p) => p.categoryId === categoryId && p.available);
}

export function getCustomerByPhone(phone: string): Customer | undefined {
  const clean = phone.replace(/\D/g, "");
  return CUSTOMERS.find((c) => c.phone.replace(/\D/g, "") === clean);
}

export function getOrderById(id: string): Order | undefined {
  return ORDERS.find((o) => o.id === id);
}

export function getEmployeeById(id: string): Employee | undefined {
  return EMPLOYEES.find((e) => e.id === id);
}
